<?php

// The public feature catalogue groups current capabilities for browsing and search.
return [
    [
        'id' => 'requests',
        'label' => 'Requests & SQL',
        'description' => 'Start with the request, find expensive work, and follow the evidence to your code.',
        'sections' => [
            [
                'id' => 'request-context',
                'title' => 'Requests',
                'description' => 'See what arrived, which code handled it, and what your application returned.',
                'docs' => 'docs.requests',
                'features' => [
                    ['title' => 'Page and API requests', 'description' => 'Capture HTML, JSON, AJAX, Livewire, redirect, download, and streamed-response requests.', 'keywords' => 'fetch xhr endpoint response'],
                    ['title' => 'Received → Matched → Responded', 'description' => 'Read the incoming request, matched route, authentication state, and response in one trace.'],
                    ['title' => 'Exact request identity', 'description' => 'Identify a profile by its method, URL, status, recording time, and ID, also returned in the X-NewDebugBar-Profile header.'],
                    ['title' => 'Headers and submitted input', 'description' => 'Inspect retained request headers, query parameters, and submitted input, then copy a detail group as JSON.', 'keywords' => 'form body payload parameters'],
                    ['title' => 'Routes and middleware', 'description' => 'Find the route name, controller or action, route parameters, and captured middleware evidence.'],
                    ['title' => 'Authentication context', 'description' => 'See the guard, guest or authenticated state, authenticatable model, and a stable hashed identity reference.', 'keywords' => 'auth user login'],
                    ['title' => 'Session structure', 'description' => 'Inspect the session driver, key names, flash keys, and validation error-bag names without dumping session values.'],
                    ['title' => 'Response details', 'description' => 'Read retained response headers, content type, status, duration, and request or response sizes where available.', 'keywords' => 'bytes errors exception'],
                ],
                'note' => 'JSON, downloads, redirects, and streams can be profiled without inserting toolbar HTML into their response bodies.',
            ],
            [
                'id' => 'timeline-performance',
                'title' => 'Timeline & performance',
                'description' => 'See when work happened and which measured operations took the most time.',
                'docs' => 'docs.performance',
                'features' => [
                    ['title' => 'Request performance at a glance', 'description' => 'Read response duration, query count, total query time, and process peak memory together.'],
                    ['title' => 'One chronological timeline', 'description' => 'Follow captured SQL, HTTP calls, models, views, logs, exceptions, events, and queue activity in time order.'],
                    ['title' => 'Waterfall and mobile detail', 'description' => 'Compare measured spans on a shared desktop time scale or use chronological activity details on smaller screens.'],
                    ['title' => 'Search and focus', 'description' => 'Search activity or source and switch between key activity, all activity, or a single inspector section.'],
                    ['title' => 'Activity details and source', 'description' => 'Inspect timestamps and available duration measurements, copy the application source, or open the related inspector.'],
                    ['title' => 'Long and incomplete timelines', 'description' => 'Load more activity as you scroll, retry failed loads, and see omitted counts when capture limits were reached.'],
                ],
                'note' => 'The timeline distinguishes timed operations from point events; it is not a CPU flame graph or a complete breakdown of exclusive time.',
            ],
            [
                'id' => 'queries-transactions',
                'title' => 'Queries & transactions',
                'description' => 'Go from a slow page to the SQL, bindings, and application call site behind it.',
                'docs' => 'docs.queries',
                'features' => [
                    ['title' => 'SQL, bindings, and source', 'description' => 'Inspect executed SQL, retained bindings, connection, duration, execution order, and the application call stack.', 'keywords' => 'database mysql postgresql sqlite'],
                    ['title' => 'Readable bound SQL', 'description' => 'Read and copy SQL with usable bound values when complete bindings were retained.'],
                    ['title' => 'Database time and query share', 'description' => 'See query totals, total database time, slow queries, and each query’s share of database and request time.'],
                    ['title' => 'Repeated query groups', 'description' => 'Group executions of the same query shape and compare their counts, timings, and binding differences.', 'keywords' => 'duplicate duplicates'],
                    ['title' => 'Likely N+1 detection', 'description' => 'Find repeated reads with changing bindings and a shared application source that suggest an N+1 problem.', 'keywords' => 'n+1 n plus one eager loading relationships'],
                    ['title' => 'Search, filter, and sort', 'description' => 'Focus on slow, repeated, read, or write queries and drill into individual executions or groups.'],
                    ['title' => 'Transaction markers', 'description' => 'Locate transaction begin, commit, and rollback events with their connection and position in the profile.'],
                    ['title' => 'EXPLAIN query plans', 'description' => 'Request a plan for eligible read-only SQL on MySQL, PostgreSQL, or SQLite, with a clear reason when a plan is unavailable.', 'keywords' => 'index indexes execution plan'],
                ],
                'note' => 'N+1 detection identifies likely patterns; EXPLAIN is an explicit local action and does not run EXPLAIN ANALYZE.',
            ],
            [
                'id' => 'automatic-findings',
                'title' => 'Automatic findings',
                'description' => 'Let captured failures and performance patterns point you toward the next useful check.',
                'docs' => 'docs.performance',
                'features' => [
                    ['title' => 'Failure leads', 'description' => 'Identify captured exceptions, failed requests or runtime operations, and failed outbound HTTP calls.'],
                    ['title' => 'Authorization and validation leads', 'description' => 'Surface denied decisions and validation failures with the relevant context and a concrete next check.'],
                    ['title' => 'Performance leads', 'description' => 'Find slow requests, slow queries, likely N+1 patterns, and repeated database work that crosses the analysis thresholds.'],
                    ['title' => 'Cache miss patterns', 'description' => 'Flag a high cache miss rate after enough reads have been captured to make the finding useful.'],
                    ['title' => 'Useful evidence and next steps', 'description' => 'Give agents structured findings with severity, an explanation, supporting evidence, a source when known, and a suggested next check.', 'keywords' => 'mcp diagnostics warnings'],
                    ['title' => 'Attention where it matters', 'description' => 'Prioritize failures before performance leads, keep relevant inspector sections active, and move attention items up in the command palette.'],
                ],
                'note' => 'Complete structured findings are available through MCP; the browser uses them to guide attention within the existing inspectors.',
            ],
        ],
    ],
    [
        'id' => 'laravel',
        'label' => 'Laravel internals',
        'description' => 'Understand the models, templates, decisions, and failures behind the response.',
        'sections' => [
            [
                'id' => 'eloquent-models',
                'title' => 'Eloquent models',
                'description' => 'Trace record loads and logical changes back to application code.',
                'docs' => 'docs.eloquent',
                'features' => [
                    ['title' => 'Record loads and writes', 'description' => 'Inspect model activity with the class, connection, table, and retained record identifiers.'],
                    ['title' => 'Model groups', 'description' => 'Group work by model and distinguish loaded records from logical change operations.'],
                    ['title' => 'Repeated record loads', 'description' => 'Spot repeated loads of identified records while keeping loads without a selected primary key visible.', 'keywords' => 'duplicate retrieval hydration'],
                    ['title' => 'Changed attributes', 'description' => 'Inspect changed attribute names and captured post-change values with visible capture limits.', 'keywords' => 'created updated deleted saved'],
                    ['title' => 'Logical changes', 'description' => 'Read related lifecycle callbacks as one logical change instead of counting every callback as another write.'],
                    ['title' => 'Related SQL and sources', 'description' => 'Search model activity, follow application call sites, and inspect query evidence correlated by source.'],
                ],
            ],
            [
                'id' => 'blade-views',
                'title' => 'Blade views',
                'description' => 'Find the templates and captured data used to build the page.',
                'docs' => 'docs.inspectors',
                'features' => [
                    ['title' => 'View occurrences', 'description' => 'See which views were composed, their order, and how often each template appeared.'],
                    ['title' => 'Application views first', 'description' => 'Group and search views, focus on application templates, and reveal framework or vendor views when needed.'],
                    ['title' => 'Original template sources', 'description' => 'Inspect and copy source paths, including original Blade sources resolved from compiled templates.'],
                    ['title' => 'View data and composers', 'description' => 'Inspect registered composer evidence and load the retained data for a selected view occurrence.'],
                ],
                'note' => 'Views record composition activity; per-template Blade render durations are not measured.',
            ],
            [
                'id' => 'events-listeners',
                'title' => 'Events & listeners',
                'description' => 'See what was dispatched and which listeners were registered to handle it.',
                'docs' => 'docs.inspectors',
                'features' => [
                    ['title' => 'Dispatched events', 'description' => 'Inspect event names, dispatch sources, broadcast markers, and sequence or timing markers.'],
                    ['title' => 'Payload shape', 'description' => 'Read argument types, public field names, counts, and truncation state without retaining event payload values.'],
                    ['title' => 'Listener registration', 'description' => 'Inspect registered listener metadata and available queued or synchronous handling evidence.'],
                    ['title' => 'Repeated events and duplicate listeners', 'description' => 'Group repeated event occurrences and spot duplicate listener registrations to check against discovery and explicit registration.'],
                    ['title' => 'Search and related activity', 'description' => 'Search event, listener, payload-shape, or source evidence and follow related framework diagnostic sections.'],
                ],
            ],
            [
                'id' => 'authorization-decisions',
                'title' => 'Authorization',
                'description' => 'Understand a Gate or policy decision in the context that produced it.',
                'docs' => 'docs.inspectors',
                'features' => [
                    ['title' => 'Gate and policy checks', 'description' => 'Inspect the ability, result, evaluated user, typed or model arguments, and application call site.', 'keywords' => 'permissions can cannot allows denies'],
                    ['title' => 'Resolved handlers', 'description' => 'Identify the policy or Gate handler and inspect available source evidence.'],
                    ['title' => 'Decision details', 'description' => 'Read available decision messages, result codes, and custom HTTP statuses, or focus on denied checks.'],
                    ['title' => 'Blade authorization sources', 'description' => 'Resolve supported Blade authorization directives to the original template line and inspect repeated checks.'],
                ],
            ],
            [
                'id' => 'validation-failures',
                'title' => 'Validation',
                'description' => 'Find the failed fields and rules without losing the request that caused them.',
                'docs' => 'docs.errors-and-logs',
                'features' => [
                    ['title' => 'Fields, rules, and messages', 'description' => 'Inspect handled validation failures with failed fields, rule names, messages, and error bags.'],
                    ['title' => 'HTTP and Livewire failures', 'description' => 'Capture HTTP validation exceptions and supported Livewire failures with available source, component, and response context.'],
                    ['title' => 'Validation across redirects', 'description' => 'Show flashed errors on the redirected page as previous-request evidence and avoid duplicating the same validation exception.'],
                ],
            ],
            [
                'id' => 'exceptions',
                'title' => 'Exceptions',
                'description' => 'Start at the failing application line and follow the cause when you need more detail.',
                'docs' => 'docs.errors-and-logs',
                'features' => [
                    ['title' => 'Exception details', 'description' => 'Inspect the captured exception class, message, file, line, and application location.', 'keywords' => 'error failure throwable'],
                    ['title' => 'Previous exception causes', 'description' => 'Follow retained exception causes to understand failures that were wrapped or rethrown.'],
                    ['title' => 'Application frames first', 'description' => 'Read your application’s stack frames first and reveal retained framework or vendor frames for deeper investigation.'],
                    ['title' => 'Source context and linked logs', 'description' => 'Read bounded code around the failing line and follow relationships to captured log entries when available.'],
                ],
            ],
            [
                'id' => 'logs',
                'title' => 'Logs',
                'description' => 'Read messages with their context, channel, and application source.',
                'docs' => 'docs.errors-and-logs',
                'features' => [
                    ['title' => 'Messages, context, and channels', 'description' => 'Inspect log level, message, timestamp, retained context, source, and available Laravel channel information.'],
                    ['title' => 'Repeated message folding', 'description' => 'Fold consecutive identical log entries while keeping their individual occurrence details accessible.'],
                    ['title' => 'Search and severity filters', 'description' => 'Search messages, context, or source, filter by severity or attention, and copy useful details.'],
                    ['title' => 'Related exceptions and mail', 'description' => 'Follow linked exception evidence and inspect logged mail content in the Mail inspector instead of a full MIME dump.'],
                ],
            ],
        ],
    ],
    [
        'id' => 'livewire',
        'label' => 'Livewire',
        'description' => 'Connect component state, browser interactions, and the server work behind each update.',
        'sections' => [
            [
                'id' => 'livewire-components',
                'title' => 'Livewire components & interactions',
                'description' => 'Explore the component tree, follow state changes, and edit supported live properties.',
                'docs' => 'docs.livewire',
                'features' => [
                    ['title' => 'Mounted component tree', 'description' => 'Browse Livewire 4 component instances, names, IDs, parent relationships, and mounted state across nested components and multiple roots.'],
                    ['title' => 'Properties and sources', 'description' => 'Inspect public property descriptors, supported browser values, component source, and view source.'],
                    ['title' => 'Client and server state', 'description' => 'Compare client values with confirmed server values and distinguish synced, dirty, updating, locked, and unconfirmed state.'],
                    ['title' => 'Server lifecycle activity', 'description' => 'Follow captured mounts, property updates, actions, renders, effects, and failures, with component metadata refreshed on each update.'],
                    ['title' => 'Browser-to-server context', 'description' => 'Connect server records with browser activity for the specific component update you are investigating.'],
                    ['title' => 'Update phases and timing', 'description' => 'Inspect browser request and update phases with available timing gaps around state synchronization and rendering.'],
                    ['title' => 'Before, submitted, and confirmed values', 'description' => 'Compare property values before an interaction, values submitted to the server, and confirmed values after the update.'],
                    ['title' => 'Actions and returned effects', 'description' => 'Follow action parameters, property changes, returned effects, and dispatched-event evidence within capture limits.'],
                    ['title' => 'Event dispatch and recipients', 'description' => 'Inspect event names, payloads, dispatch modes, declared targets, and observed recipient components.'],
                    ['title' => 'Bundled interactions', 'description' => 'Inspect bundled component interactions individually while keeping their shared HTTP profile linked.'],
                    ['title' => 'Rendering and grouped activity', 'description' => 'Read related lifecycle records as component activity, including initial and later render-duration evidence.'],
                    ['title' => 'Focused component workspaces', 'description' => 'Search components and activity, then switch between focused property, source, and interaction details.'],
                    ['title' => 'Live property editing', 'description' => 'Edit supported primitive public properties and eligible primitive array values on a currently mounted component.', 'keywords' => 'boolean string integer float null array state'],
                    ['title' => 'Checked edits with Apply and Cancel', 'description' => 'Use type-aware controls with editability and stale-value checks, then apply a real Livewire update and inspect its request.'],
                ],
                'note' => 'Property edits can trigger normal application behavior; live browser state and browser-only traces are not all saved in server profiles.',
            ],
        ],
    ],
    [
        'id' => 'services',
        'label' => 'Connected services',
        'description' => 'Follow outbound calls, cached data, background jobs, and messages from the same request.',
        'sections' => [
            [
                'id' => 'outbound-http',
                'title' => 'HTTP client',
                'description' => 'See the outbound request, the response, and the code that made the call.',
                'docs' => 'docs.http-client',
                'features' => [
                    ['title' => 'Outbound Laravel HTTP calls', 'description' => 'Capture method, URL, host, status, start and finish timing, and duration for Laravel HTTP-client requests.'],
                    ['title' => 'Request and response content', 'description' => 'Inspect retained headers and bounded text or JSON bodies in dedicated request and response views.'],
                    ['title' => 'Connection failures and redirects', 'description' => 'Inspect failures even without a response, and see redirect Location targets when captured.'],
                    ['title' => 'Slow calls and response guidance', 'description' => 'Identify slow or failed calls and get response-specific checks for authentication, permissions, validation, rate limits, and server errors.'],
                    ['title' => 'Search and application sources', 'description' => 'Search, filter, and sort outbound calls, then inspect the application call site and retained stack.'],
                    ['title' => 'Copy as cURL', 'description' => 'Copy a sanitized cURL representation for supported captured requests.', 'keywords' => 'curl terminal reproduce api'],
                ],
                'note' => 'Capture follows Laravel HTTP-client events; multipart and binary bodies are omitted, and copied cURL reflects retained content.',
            ],
            [
                'id' => 'cache',
                'title' => 'Cache',
                'description' => 'Find misses, repeated lookups, and failed operations with their original application source.',
                'docs' => 'docs.cache-and-redis',
                'features' => [
                    ['title' => 'Cache operations and outcomes', 'description' => 'Inspect Laravel cache reads, writes, forget or delete operations, and flushes with their captured outcomes.'],
                    ['title' => 'Hits, misses, and repeated misses', 'description' => 'See total reads, hit and miss rates, and repeated misses grouped by key.'],
                    ['title' => 'Keys, values, tags, and expiry', 'description' => 'Inspect the store, retained keys and values, tags, TTL or expiry metadata, and application source where captured.'],
                    ['title' => 'Batch, failure, and failover evidence', 'description' => 'Inspect available batch context, operation timing, write or delete failures, and store failover evidence.'],
                    ['title' => 'Search and operation details', 'description' => 'Search or filter cache activity and drill into individual operations and repeated-miss groups.'],
                ],
            ],
            [
                'id' => 'redis',
                'title' => 'Redis',
                'description' => 'Inspect direct Redis commands without counting captured cache work twice.',
                'docs' => 'docs.cache-and-redis',
                'features' => [
                    ['title' => 'Direct Redis command details', 'description' => 'See the command, connection, recognized command keys, duration, failure state, and available exception class.'],
                    ['title' => 'Cache operation deduplication', 'description' => 'Remove matching Redis records already represented by Laravel cache events.'],
                    ['title' => 'Search and command sources', 'description' => 'Search or filter direct command activity and follow the application call site for each operation.'],
                ],
                'note' => 'Recognized keys are retained within limits; arbitrary command arguments, field values, and return values are not captured.',
            ],
            [
                'id' => 'queues-background',
                'title' => 'Queues & background work',
                'description' => 'Follow a dispatch beyond the response to its captured worker attempts and outcome.',
                'docs' => 'docs.queues',
                'features' => [
                    ['title' => 'Dispatched jobs', 'description' => 'Inspect job class, connection, queue, delay, identity, attempts, and captured timing.'],
                    ['title' => 'Dispatch and execution', 'description' => 'Distinguish dispatch activity, synchronous execution, and asynchronous worker outcomes.'],
                    ['title' => 'Linked worker profiles', 'description' => 'Follow correlated worker profiles and attempts from the originating request, or return to that request.'],
                    ['title' => 'Attempts, releases, and retries', 'description' => 'Inspect waiting, completed, and failed states, recent attempts, released jobs, and retryable failures.'],
                    ['title' => 'Queued mail and notifications', 'description' => 'Inspect queued message metadata and open a linked mail preview or worker profile when available.'],
                    ['title' => 'Pending outcome refresh', 'description' => 'Check manually for newer worker outcomes or let the open inspector refresh pending work within a bounded polling window.'],
                    ['title' => 'Work after the response', 'description' => 'Capture supported work during request termination with separate timing, and search or filter queue activity by job, queue, or outcome.'],
                ],
                'note' => 'Cross-process links need profiling in the worker environment and access to the relevant retained profiles and correlation data.',
            ],
            [
                'id' => 'mail',
                'title' => 'Mail',
                'description' => 'Read the message your application produced, including previews and retained attachments.',
                'docs' => 'docs.mail-and-notifications',
                'features' => [
                    ['title' => 'Message and transport details', 'description' => 'Inspect subject, mailable, sender, recipients, reply-to, date, priority, return path, source, and available mailer, transport, message ID, and sending duration.'],
                    ['title' => 'HTML and text previews', 'description' => 'Open local previews of HTML and plain-text bodies captured automatically within the body limits.'],
                    ['title' => 'Isolated HTML preview', 'description' => 'Read HTML mail in a sandbox with remote resource loading blocked.'],
                    ['title' => 'Download as .eml', 'description' => 'Download a reconstructed message file from the retained mail content.', 'keywords' => 'email export message mime'],
                    ['title' => 'Attachment downloads', 'description' => 'Inspect attachment metadata and download retained attachment bodies within the per-message budget.'],
                    ['title' => 'Queued outcomes and capture limits', 'description' => 'Follow available queued-mail outcomes and see when previews or attachment contents were truncated or unavailable.'],
                ],
            ],
            [
                'id' => 'notifications',
                'title' => 'Notifications',
                'description' => 'Read a logical notification and the individual channel attempts behind it.',
                'docs' => 'docs.mail-and-notifications',
                'features' => [
                    ['title' => 'Grouped channel attempts', 'description' => 'Group notification activity and inspect the class, recipient context, channel, and application source.'],
                    ['title' => 'Content and destination evidence', 'description' => 'Read bounded public notification data, channel destination, returned response evidence, and captured timing.'],
                    ['title' => 'Delivery activity and failures', 'description' => 'Distinguish captured queued, pending, sent, and failed activity and inspect channel failure details.'],
                    ['title' => 'Related mail and worker profiles', 'description' => 'Search or filter notifications and follow a related mail record or worker profile when correlation is available.'],
                ],
                'note' => 'Channel detail depends on the events available; a sent or completed event does not prove receipt by the recipient.',
            ],
        ],
    ],
    [
        'id' => 'agents',
        'label' => 'Agents & testing',
        'description' => 'Give coding agents exact debugging context and turn performance expectations into tests.',
        'sections' => [
            [
                'id' => 'mcp-agents',
                'title' => 'Local MCP for coding agents',
                'description' => 'Give agents exact saved evidence in focused responses, helping reduce guessing and token use.',
                'docs' => 'docs.mcp',
                'features' => [
                    ['title' => 'Discover the right profile', 'description' => 'Use list-debug-profiles to filter retained profiles by method, path, status, or warnings, or use an exact response profile ID.'],
                    ['title' => 'Read focused inspector evidence', 'description' => 'Use get-debug-profile-section for a bounded summary and a page of evidence from a chosen inspector.'],
                    ['title' => 'Get findings and next checks', 'description' => 'Use get-debug-findings to read structured diagnostic leads, supporting evidence, and suggested next steps.'],
                    ['title' => 'Investigate SQL directly', 'description' => 'Use inspect-debug-queries to search, filter, sort, and page through all, repeated, slow, read, or write queries.'],
                    ['title' => 'Reach deeper retained values', 'description' => 'Use get-debug-profile-data to follow returned JSON Pointer paths into nested or derived evidence and read large retained strings in chunks.'],
                    ['title' => 'Local clients and bounded responses', 'description' => 'Connect local stdio clients such as Claude Code, Cursor, or VS Code, with paged responses and explicit errors for failed profile processing.'],
                ],
                'note' => 'All five MCP tools are read-only and can retrieve only data retained after capture-time redaction and limits.',
            ],
            [
                'id' => 'runtime-profiles',
                'title' => 'Command & worker profiles',
                'description' => 'Bring supported work outside HTTP requests into the same diagnostic interface.',
                'docs' => 'docs.testing',
                'features' => [
                    ['title' => 'Artisan command profiles', 'description' => 'Automatically profile supported Artisan command lifecycles with operation name, runtime context, exit code, duration, and captured diagnostics.'],
                    ['title' => 'Test-command context', 'description' => 'Recognize the Artisan test command as a test-command profile for captured activity in the profiled process.', 'keywords' => 'pest phpunit tests cli'],
                    ['title' => 'Individual worker-job profiles', 'description' => 'Inspect worker jobs with linked attempt context, supported collector activity, and originating-request relationships through MCP or available browser links.'],
                ],
                'note' => 'Test-command profiles are command-level context, not per-test-case tracing or guaranteed capture of child-process activity.',
            ],
            [
                'id' => 'profile-assertions',
                'title' => 'Profile assertions',
                'description' => 'Catch expensive request changes in your Laravel tests.',
                'docs' => 'docs.testing',
                'features' => [
                    ['title' => 'Fluent profile assertions', 'description' => 'Build assertions from a supplied profile or a stored profile ID in your existing Laravel tests.'],
                    ['title' => 'Query count and time budgets', 'description' => 'Set maximum query count and total query time with assertQueryCountAtMost() and assertQueryTimeAtMost().'],
                    ['title' => 'Duration and peak-memory budgets', 'description' => 'Set maximum duration and process peak memory with assertDurationAtMost() and assertPeakMemoryAtMost().'],
                    ['title' => 'Repeated-query and N+1 checks', 'description' => 'Assert that repeated query patterns and likely N+1 findings are absent with dedicated assertions.'],
                ],
            ],
        ],
    ],
    [
        'id' => 'workflow',
        'label' => 'Everyday workflow',
        'description' => 'Keep debugging close to your application, with useful defaults and details on demand.',
        'sections' => [
            [
                'id' => 'browser-workflow',
                'title' => 'Browser workflow',
                'description' => 'Stay on the page while you move between requests and the evidence you need.',
                'docs' => 'docs.requests',
                'features' => [
                    ['title' => 'Compact toolbar, deep inspector', 'description' => 'Keep request, query, and timing information close at hand, then expand the inspector for detailed evidence.'],
                    ['title' => 'Toolbar placement', 'description' => 'Move the toolbar to the top, bottom, or a corner by dragging or using keyboard-accessible commands.'],
                    ['title' => 'Light, dark, and system themes', 'description' => 'Choose an appearance and keep that preference saved in the browser.'],
                    ['title' => 'Favorites and command palette', 'description' => 'Favorite and reorder sections, or press Command/Ctrl + Shift + P to search sections and available actions.'],
                    ['title' => 'Same-page request discovery', 'description' => 'Choose later fetch, XHR, and Livewire profiles without leaving the page, while preserving your choice when background requests arrive.'],
                    ['title' => 'Navigation support', 'description' => 'Continue through supported Livewire navigation and follow foreground Inertia visits while keeping partial reloads as background profiles.'],
                    ['title' => 'Readable, copyable evidence', 'description' => 'Read highlighted SQL, JSON, HTTP, and PHP, then copy SQL, structured data, or source locations with visible controls.'],
                    ['title' => 'Responsive and keyboard-friendly controls', 'description' => 'Use responsive list and detail navigation, focus handling, keyboard controls, and reduced-motion behavior.'],
                    ['title' => 'Host-page isolation and recovery', 'description' => 'Keep package assets and themes scoped, adjust around visible host dialogs, and recover toolbar-owned requests from stale CSRF tokens.'],
                ],
                'note' => 'The request picker shows profiles discovered on the current page; source controls copy a location.',
            ],
            [
                'id' => 'local-setup',
                'title' => 'Local setup & retained data',
                'description' => 'Start with a complete local debugging experience and inspect the runtime behind it.',
                'docs' => 'docs.configuration',
                'features' => [
                    ['title' => 'Install and start debugging', 'description' => 'Add the Laravel development dependency with automatic provider registration, local HTML injection, and diagnostic collectors enabled in the local environment.'],
                    ['title' => 'Free and open source', 'description' => 'Use the New Debug Bar under the Apache License 2.0.'],
                    ['title' => 'Local files, automatic retention', 'description' => 'Store profiles in local files with automatic age and count limits, without a package database migration.'],
                    ['title' => 'Runtime and framework context', 'description' => 'Inspect PHP, Laravel, and package versions, runtime type, locale, timezone, debug mode, driver names, and configuration, route, or event cache state.'],
                    ['title' => 'Useful local values by default', 'description' => 'Keep local SQL bindings and cache or Redis keys available, with explicit alternative capture policies.'],
                    ['title' => 'Adjust the limits that matter', 'description' => 'Publish configuration to change environments, thresholds, storage, retention, and capture limits, with omitted data reported.'],
                    ['title' => 'Application lifecycle isolation', 'description' => 'Skip the debugger’s own traffic, reset collector state between lifecycles, and preserve the host response when guarded profiling setup or capture fails.'],
                ],
            ],
        ],
    ],
];
