name: Deploy to Production

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to production
        run: curl -X POST ${{ secrets.PRODUCTION_DEPLOYMENT_URL }}
